/**
 * Generated by @openapi-codegen
 *
 * @version 20170710.0
 */
import type * as Schemas from './schemas'

export type Unauthorized = Schemas.BaseError

export type UnprocessableEntity = Schemas.BaseError
